---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-dotne1t
  labels:
    app: hello-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-dotnet
  template:
    metadata:
      labels:
        app: hello-dotnet
    spec:
      containers:
      - name: hello-dotnet1
        image: sai06/hello-dotnet:latest
        ports:
        - containerPort: 8080
