---
apiVersion: v1
kind: Service
metadata:
  name: hello-dotnet
  labels:
    app: hello-dotnet
spec:
  ports:
  - name: client
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer    
  selector:
    app: hello-dotnet
